### ISSUE TITLE
Add call for papers to KG

### ISSUE THREAD

**Issue by pheyvaer** [kgb-workshop/sad-generator#15]
Currently, the call for papers is only available in the HTML. It should also be added to the KG and then read from the KG to put it in the website.

**Comment by pheyvaer** [comment]
Suggestion: I would not store this text in a CSV file, because that hard to edit. An option would to store it in a plain txt file.

**Comment by dachafra** [comment]
How should we access to the cfp if it is in a plain text file? Are rmlmapper able to get that data?

**Comment by pheyvaer** [comment]
I created a function for that described with FnO. Not yet available in the latest release tho, but I can give you a local build :)

**Comment by dachafra** [comment]
Example of mapping with that function would be enough

**Comment by pheyvaer** [comment]
Here you go:

```
- p: ex:cfp
  o:
    - function: idlab-fn:readFile
      parameters:
        - [idlab-fn:path, "cfp.txt"]
```
